---
- name: Playbook for SNOW Integration
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:

  - name: Set Concerns Message
    ansible.builtin.set_fact:
      snow_change_message: "{{ lookup('ansible.builtin.template', 'templates/snow_message.j2') }}"

  - name: Create change request
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"

      type: "{{ change_type | default('normal') }}"
      short_description: "{{ cr_short_description }}"
      description: >-
        {{ tower_user_name }} requests {{ snow_change_message }}
      priority: high
      risk: low
      impact: low
      assignment_group: CAB Approval
      state: assess
      # requested_by: "{{ tower_user_name }}"
    register: request
    until: request.changed is defined
    retries: 5
    delay: 5
    delegate_to: localhost

  - name: Change Request is raised
    set_fact:
      msg: >- 
        A change request has been raised. 
        Please click on this URL to review: <{{ servicenow_hostname }}/nav_to.do?uri=change_request.do?sysparm_query=number={{request.record.number }}

  - name: Pass along request information
    ansible.builtin.set_stats:
      data:
        request: "{{ request }}"
      per_host: false
    delegate_to: localhost
    
  - name: Wait for Change Request approval
    servicenow.itsm.change_request_info:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      number: "{{ request.record.number }}"
    until: change_request_status.records[0].state == "scheduled"
    retries: 50
    delay: 10
    register: change_request_status
    delegate_to: localhost
    when: 
      - change_type is defined
      - change_type == 'normal'

  - name: Update to implement the change request in ServiceNow
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      state: scheduled
      number: "{{ request.record.number }}"
      assignment_group: CAB Approval
    delegate_to: localhost
    when: 
      - change_type is defined
      - change_type == 'standard'

  - name: Update to implement the change request in ServiceNow
    servicenow.itsm.change_request:
      instance:
        host: "{{ servicenow_hostname }}"
        username: "{{ servicenow_username }}"
        password: "{{ servicenow_password }}"
      state: implement
      number: "{{ request.record.number }}"
      assignment_group: CAB Approval
    delegate_to: localhost




