---
- name: Deploy Azure instance using terraform
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - cloud.terraform

  vars:
    project_dir: '/tmp/deployment'

  tasks:
    - name: Grab instance info
      ansible.builtin.git:
       repo: https://github.com/sonstar2/multi-cloud-aap-terraform.git
       dest: '{{ project_dir }}'

    - name: Set Password Variable
      set_fact:
        ansible_admin_pass: "{{ ansible_password }}"
      no_log: true

    - name: Deploy terraform userdata file
      ansible.builtin.template:
        src: terraform/terraform-azure/windows_userdata.ps1
        dest: '{{ project_dir }}/terraform/terraform-azure/windows_userdata.ps1'
  
    - name: Deploy terraform variable file
      ansible.builtin.template:
        src: terraform/terraform-azure/main.tf
        dest: '{{ project_dir }}/terraform/terraform-azure/main.tf'

    - name: Deploy with force init
      cloud.terraform.terraform:
        project_path: '{{ project_dir }}/terraform/terraform-azure'
        state: present
        force_init: true
        backend_config_files:
          - "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"