---
- name: Deploy Azure instance using terraform
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
    - cloud.terraform

  vars:
    project_dir: '/tmp/deployment'

  tasks:
    - name: Grab instance info
      ansible.builtin.git:
       repo: https://github.com/sonstar2/multi-cloud-aap-terraform.git
       dest: '{{ project_dir }}'

    - name: Debug backend_config_files
      debug: 
        msg: "{{ lookup('ansible.builtin.env', 'TF_BACKEND_CONFIG_FILE') }}"


    - name: Deploy with force init
      cloud.terraform.terraform:
        project_path: '{{ project_dir }}/terraform/terraform-gce'
        state: present
        force_init: true
        backend_config_files:
          - "{{ lookup('env', 'TF_BACKEND_CONFIG_FILE') }}"
